version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Build phase complete (CLI app, no build needed)"
  post_build:
    commands:
      - echo "Deploying to EC2"
      - chmod 400 xfx.pem
      - |
        scp -o StrictHostKeyChecking=no -i xfx.pem deploy.sh ec2-user@13.232.203.69:/home/ec2-user/
        ssh -o StrictHostKeyChecking=no -i xfx.pem ec2-user@13.232.203.69 "bash deploy.sh"
