version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "📦 Installing Python dependencies..."
      - pip install -r requirements.txt || true

  build:
    commands:
      - echo "🔍 Build phase - optionally lint or package the app"

  post_build:
    commands:
      - echo "✅ Running tests with Pytest..."
      - pytest || echo "⚠️ No tests found or failed, continuing..."

artifacts:
  files:
    - '**/*'
